apiVersion: v1
data:
  password: bWFoaW1ha3Vsa2Fybmk=
  username: ZTg5YmY2NDE5ZTZkYzg1N2RlOWJlMWUyZTQ1NGVjOTMzNmM5MGRjMQ==
kind: Secret
metadata:
  name: pipeline-server-git
  namespace: kabanero
type: kubernetes.io/basic-auth
