apiVersion: v1
data:
  password: ZTg5YmY2NDE5ZTZkYzg1N2RlOWJlMWUyZTQ1NGVjOTMzNmM5MGRjMQ==
  username: bWFoaW1ha3Vsa2Fybmk=
kind: Secret
metadata:
  name: pipeline-server-git
  namespace: kabanero
type: kubernetes.io/basic-auth
