apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: custom-java-spring-boot2-sonarqube-task
  namespace: kabanero
  author: Hemankita Perabathini
spec:
  inputs:
    resources:
      - name: git-source
        type: git
    params:
      - name: maven-image
        type: string
        default: kabanero/java-spring-boot2:0.3
  steps:
    - resources: {}
      name: appsody-extract
      command:
        - /bin/bash
      env:
        - name: SONARQUBE_URL
          valueFrom:
            configMapKeyRef:
              key: SONARQUBE_URL
              name: sonarqube-config
              optional: true
        - name: SONARQUBE_LOGIN
          valueFrom:
            secretKeyRef:
              key: SONARQUBE_LOGIN
              name: sonarqube-access
              optional: true
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
      image: 'appsody/appsody-buildah:0.5.8-buildah1.9.0'
      workingDir: $(inputs.resources.git-source.path)
      args:
        - '-c'
        - |
          set -e

          if [ "${SONARQUBE_URL}" == "url" ]; then
              echo "Skipping SonarQube tests - SonarQube not configured"
          elif [ -z "${SONARQUBE_LOGIN}" ]; then
              echo "Skipping SonarQube tests - SonarQube credentials not found"
          else
              appsody extract --buildah --target-dir ./sonarscan
              echo "Appsody extract completed"
          fi
    - resources: {}
      name: sonarqube
      command:
        - /bin/bash
      env:
        - name: SONARQUBE_URL
          valueFrom:
            configMapKeyRef:
              key: SONARQUBE_URL
              name: sonarqube-config
              optional: true
        - name: SONARQUBE_LOGIN
          valueFrom:
            secretKeyRef:
              key: SONARQUBE_LOGIN
              name: sonarqube-access
              optional: true
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: .m2/repository
          name: m2-repository
      image: $(inputs.params.maven-image)
      workingDir: $(inputs.resources.git-source.path)
      args:
        - '-c'
        - |
          set -e
              echo "Starting sonar scan"
              cd /workspace/git-source/sonarscan/user-app
              mvn install -Dmaven.test.skip=true sonar:sonar -Dsonar.host.url="${SONARQUBE_URL}" -Dsonar.login="${SONARQUBE_LOGIN}"
  volumes:
    - emptyDir: {}
      name: m2-repository
    - name: varlibcontainers
