apiVersion: v1
data:
  SONARQUBE_URL: https://sonarqube-atci-cp4a-cicd.cp4appl-demo-cluster-atci-83bcef15400c39e8de4fdef573e95a5c-0000.us-south.containers.appdomain.cloud
kind: ConfigMap
metadata:
  annotations:
    description: Config map to hold the url for sonarqube in the environment so that
      other components can access it
  labels:
    app: sonarqube
    app.kubernetes.io/component: tools
    app.kubernetes.io/instance: sonarqube
    app.kubernetes.io/name: sonarqube
    release: sonarqube
  name: sonarqube-config
  namespace: kabanero